name: Build and Push Docker Images

on:
  push:
    branches:
      - master
      - dev

jobs:
  build_and_push:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Build Dev Docker image
        run: docker build -t riyazkhan774/backend:dev-$(git rev-parse --short HEAD) .

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Push Dev Docker image
        run: docker push riyazkhan774/backend:dev-$(git rev-parse --short HEAD)

      - name: Update package.json version
        run: npm version patch

      - name: Build Prod Docker image
        run: docker build -t riyazkhan774/backend:latest .

      - name: Push Prod Docker image
        run: docker push riyazkhan774/backend:latest

      - name: Update package.json version
        run: npm version patch
